build:
	gcc main.c file_handling.c user_handling.c -o app.out

run:
	./app.out

debug:
	gcc -g main.c file_handling.c user_handling.c -o debugApp.out

cleanExecutables:
	rm app.out 
	rm debugApp.out
	clear

cleanAppData:
	rm AppData/*
	clear